module.exports = {
  locales: [
    {
      id: 1,
      name: "English (en)",
      code: "en",
      isDefault: false,
    },
    {
      id: 2,
      name: "Finnish (fi)",
      code: "fi",
      isDefault: true,
    },
    {
      id: 3,
      name: "Swedish (sv)",
      code: "sv",
      isDefault: false,
    },
  ],
  headers: [
    {
      id: 1,
      locale: "fi",
      text: "Nostot",
      type: "nostot",
    },
    {
      id: 2,
      locale: "en",
      text: "Highlights",
      type: "nostot",
    },
    {
      id: 14,
      locale: "sv",
      text: "Höjdpunkter",
      type: "nostot",
    },
    {
      id: 3,
      locale: "fi",
      text: "Tiedotteet",
      type: "tiedotteet",
    },
    {
      id: 4,
      locale: "en",
      text: "Bulletin",
      type: "tiedotteet",
    },
    {
      id: 15,
      locale: "sv",
      text: "Meddelande",
      type: "tiedotteet",
    },
    {
      id: 5,
      locale: "fi",
      text: "Liikennetiedotteet",
      type: "liikennetiedotteet",
    },
    {
      id: 6,
      locale: "en",
      text: "Traffic announcements",
      type: "liikennetiedotteet",
    },
    {
      id: 16,
      locale: "sv",
      text: "Trafikmeddelanden",
      type: "liikennetiedotteet",
    },
    {
      id: 7,
      locale: "fi",
      text: "Turku sovellus",
      type: "sovellus",
    },
    {
      id: 8,
      locale: "en",
      text: "Turku application",
      type: "sovellus",
    },
    {
      id: 13,
      locale: "sv",
      text: "Åbo applikation",
      type: "sovellus",
    },
    {
      id: 9,
      locale: "fi",
      text: "Kerrokantasi",
      type: "kerrokantasi",
    },
    {
      id: 10,
      locale: "en",
      text: "Voice your opinion",
      type: "kerrokantasi",
    },
    {
      id: 17,
      locale: "sv",
      text: "Säg din åsikt",
      type: "kerrokantasi",
    },
    {
      id: 11,
      locale: "fi",
      text: "Tapahtumat",
      type: "tapahtumat",
    },
    {
      id: 12,
      locale: "en",
      text: "What's happening in Turku",
      type: "tapahtumat",
    },
    {
      id: 18,
      locale: "sv",
      text: "Vad händer i Åbo",
      type: "tapahtumat",
    },
  ],
};
