import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import type { GetStaticProps } from 'next';
import ListWidget from 'components/ListWidget';
import KerroKantasiWidget from 'components/kerrokantasi/KerroKantasiWidget';

const Home = ({ locale }: { locale: Lang }) => {
  return (
    <div>
      <Head>
        <title>Turku-Sovellus</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h2>Welcome to Turku-Sovellus!</h2>

        <ListWidget
          title="Nostot"
          readMoreText="Lue lisää"
          readMoreHref="https://google.com"
          variant="primary"
        />

        <KerroKantasiWidget locale={locale} />

        <div>
          <Link href="/liikennetiedotteet" passHref>
            <a>
              <h3>Liikennetiedotteet &rarr;</h3>
            </a>
          </Link>

          <Link href="/kerrokantasi" passHref>
            <a>
              <h3>Kerrokantasi &rarr;</h3>
            </a>
          </Link>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      locale: locale || 'fi',
    },
  };
};

export default Home;
