import Head from 'next/head';
import type { GetStaticProps } from 'next';
import KerroKantasiWidget from 'components/kerrokantasi/KerroKantasiWidget';
import TurussaTapahtuuWidget from 'components/turussatapahtuu/TurussaTapahtuuWidget';
import LiikenneTiedotteetWidget from 'components/LiikenneTiedotteet/LiikenneTiedotteetWidget';
import { Grid } from '@mui/material';

const Home = ({ locale }: { locale: Lang }) => {
  return (
    <div>
      <Head>
        <title>Turku-Sovellus</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Grid
          container
          sx={{ marginBottom: '16px' }}
          columnSpacing={{ xs: 1, sm: 2, md: 3 }}
          rowSpacing={2}
        >
          <Grid item xs={12} md={6}>
            <TurussaTapahtuuWidget locale={locale} />
          </Grid>
          <Grid item xs={12} md={6}>
            <KerroKantasiWidget locale={locale} />
          </Grid>
          <Grid item xs={12} md={6}>
            <LiikenneTiedotteetWidget locale={locale} />
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      locale: locale || 'fi',
    },
  };
};

export default Home;
