import KerroKantasiCard from 'components/kerrokantasi/KerroKantasiCard';
import type { GetStaticProps } from 'next';
import Head from 'next/head';
import useKerroKantasi from 'hooks/useKerroKantasi';
import { useTitle } from 'hooks/useTitles';
import { Titles } from 'enums/titles';
import strapiClient from 'functions/strapi-client';
import { dehydrate, QueryClient } from 'react-query';

const Kerrokantasi = ({ locale }: { locale: Lang }) => {
  const { data: title } = useTitle(Titles.Kerrokantasi);
  const { isLoading, data } = useKerroKantasi();

  return (
    <div>
      <Head>
        <title>{title || 'Kerrokantasi'}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        {!isLoading &&
          data &&
          data?.map((hearing) => (
            <KerroKantasiCard hearing={hearing} locale={locale} key={hearing.id} />
          ))}
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const queryClient = new QueryClient();
  queryClient.prefetchQuery(['getTitle', Titles.Kerrokantasi], () =>
    strapiClient.titles.get(Titles.Kerrokantasi, locale || 'fi')
  );
  return {
    props: {
      locale: locale || 'fi',
      dehydratedState: dehydrate(queryClient),
    },
  };
};
export default Kerrokantasi;
