import KerroKantasiCard from 'components/KerroKantasiCard';
import type { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import useKerroKantasi from '../hooks/useKerroKantasi';

const Kerrokantasi = ({ locale }: { locale: Lang }) => {
  const { isLoading, data } = useKerroKantasi();
  console.log(data, isLoading);

  return (
    <div>
      <Head>
        <title>Kerrokantasi</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h2>Welcome to Kerrokantasi!</h2>

        <div>
          <Link href="/" passHref>
            <a>
              <h3>Etusivu &rarr;</h3>
            </a>
          </Link>
        </div>
        {!isLoading &&
          data &&
          data.map((hearing) => (
            <KerroKantasiCard hearing={hearing} locale={locale} key={hearing.id} />
          ))}
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      locale: locale || 'fi',
    },
  };
};

export default Kerrokantasi;
