import KerroKantasiCard from 'components/kerrokantasi/KerroKantasiCard';
import type { GetStaticProps } from 'next';
import Head from 'next/head';
import useKerroKantasi from 'hooks/useKerroKantasi';

const Kerrokantasi = ({ locale }: { locale: Lang }) => {
  const { isLoading, data } = useKerroKantasi();

  return (
    <div>
      <Head>
        <title>Kerrokantasi</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        {!isLoading &&
          data &&
          data.map((hearing) => (
            <KerroKantasiCard hearing={hearing} locale={locale} key={hearing.id} />
          ))}
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      locale: locale || 'fi',
    },
  };
};

export default Kerrokantasi;
