import strapiClient from 'functions/strapi-client';
import { useTitle } from 'hooks/useTitles';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { dehydrate, QueryClient } from 'react-query';

const Liikennetiedotteet: NextPage = () => {
  const { data: title } = useTitle('Liikennetiedotteet');
  console.log(title?.data);
  return (
    <div>
      <Head>
        <title>Liikennetiedotteet</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h2>Welcome to Liikennetiedotteet!</h2>

        <div>
          <Link href="/" passHref>
            <a>
              <h3>Etusivu &rarr;</h3>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const queryClient = new QueryClient();

  const { locale } = context;
  await queryClient.prefetchQuery(
    ['getTitle', 'liikennetiedotteet'],
    strapiClient.titles.get('liikennetiedotteet', locale || 'fi') as any
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default Liikennetiedotteet;
