import NostotCard from 'components/nostot/NostotCard';
import { useNostot } from 'hooks/useNostot';
import type { GetStaticProps } from 'next';
import Head from 'next/head';

const Nostot = ({ locale }: { locale: Lang }) => {
  const { isLoading, data } = useNostot();

  return (
    <div>
      <Head>
        <title>Nostot</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        {!isLoading &&
          data &&
          data?.data?.data?.map((nosto) => (
            <NostotCard nosto={nosto} locale={locale} key={nosto.id} />
          ))}
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      locale: locale || 'fi',
    },
  };
};

export default Nostot;
