name: Quality check (lint files and run e2e tests)

on: [pull_request]

jobs:
  lint_files:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
        path: ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./client
          # next build also checks for TypeScript errors and lints files
          build: npm run build
          start: npm start
